kubectl delete service coo
kubectl delete deployment coo
kubectl delete service hornet
kubectl delete deployment hornet
kubectl delete secret sh.helm.release.v1.test-chart.v1
kubectl delete secret tree-root
kubectl delete service entry
kubectl delete deployment entry
kubectl delete configmap entry-config
kubectl delete configmap hornet-config
kubectl delete configmap coo-config
kubectl delete secret entry-seed
