# Default values for private-tangle.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullPolicy: Always

coo:
  image:
    repository: sadjy/devhornet2
    # Replaced official image with custom image with curl, jq and tcpdump for debug
    tag: latest
  params:
    securityLevel: 2
    depth: 5
    mwm: 9
  ports:
    api: 14265
    peering: 15600  

hornet:
  image:
    repository: sadjy/devhornet2
    tag: latest
  replicas: 2
  ports:
    api: 14265
    peering: 15600  
  spammer:
    enabled: true
    cpuMaxUsage: 0.5
    rateLimit: 0

entry:
  image:
    repository: sadjy/devhornet2
    tag: latest
  replicas: 2
  ports:
    autopeering: 14626

seed: 

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
