apiVersion: v1
kind: Service
metadata:
  name: coo
  labels:
    app: coo
    role: coordinator
    tier: backend
spec:
  ports:
  - port: 14265
    targetPort: 14265
  selector:
    app: coo
    role: coordinator
    tier: backend
