apiVersion: v1
kind: Service
metadata:
  name: entry
  labels:
    app: entry
    role: entry
    tier: backend
spec:
  ports:
  - name: autopeering
    port: {{ .Values.entry.ports.autopeering }}
    targetPort: {{ .Values.entry.ports.autopeering }}
  - name: autopeering2
    port: {{ .Values.entry.ports.autopeering }}
    targetPort: {{ .Values.entry.ports.autopeering }}
    protocol: UDP
  selector:
    app: entry
    role: entry
    tier: backend
  clusterIP: 10.100.0.100