apiVersion: v1
kind: Service
metadata:
  name: hornet
  labels:
    app: hornet
    role: node
    tier: backend
spec:
  ports:
  - port: 14265
    targetPort: 14265
  selector:
    app: hornet
    role: node
    tier: backend