apiVersion: v1
kind: ConfigMap
metadata:
  name: hornet-config
data:
  config.json: |-
    {
      "useProfile": "auto",
      "httpAPI": {
        "basicAuth": {
          "enabled": false,
          "username": "admin",
          "passwordHash": "",
          "passwordSalt": ""
        },
        "excludeHealthCheckFromAuth": true,
        "permitRemoteAccess": [
          "getNodeInfo",
          "getBalances",
          "checkConsistency",
          "getTransactionsToApprove",
          "getInclusionStates",
          "getNodeAPIConfiguration",
          "wereAddressesSpentFrom",
          "broadcastTransactions",
          "findTransactions",
          "storeTransactions",
          "getTrytes"
        ],
        "permittedRoutes": [
          "healthz"
        ],
        "whitelistedAddresses": [],
        "bindAddress": "0.0.0.0:14265",
        "limits": {
          "bodyLengthBytes": 10000000,
          "findTransactions": 2000,
          "getTrytes": 2000,
          "requestsList": 2000
        }
      },
      "dashboard": {
        "bindAddress": "0.0.0.0:8081",
        "theme": "default",
        "dev": false,
        "basicAuth": {
          "enabled": true,
          "username": "admin",
          "passwordHash": "",
          "passwordSalt": ""
        }
      },
      "db": {
        "path": "./data/ptdb",
        "debug": false
      },
      "snapshots": {
        "loadType": "global",
        "local": {},
        "global": {
          "path": "./data/snapshot.csv",
          "spentAddressesPaths": [],
          "index": 0
        },
        "pruning": {
          "enabled": true,
          "delay": 500
        }
      },
      "spentAddresses": {
        "enabled": false
      },
      "network": {
        "preferIPv6": false,
        "gossip": {
          "bindAddress": "0.0.0.0:15600",
          "reconnectAttemptIntervalSeconds": 60
        },
        "autopeering": {
          "bindAddress": "0.0.0.0:14626",
          "runAsEntryNode": false,
          "entryNodes": [],
          "seed": ""
        }
      },
      "tipsel": {
        "maxDeltaTxYoungestRootSnapshotIndexToLSMI": 8,
        "maxDeltaTxOldestRootSnapshotIndexToLSMI": 13,
        "belowMaxDepth": 15,
        "nonLazy": {
          "retentionRulesTipsLimit": 100,
          "maxReferencedTipAgeSeconds": 3,
          "maxApprovers": 2
        },
        "semiLazy": {
          "retentionRulesTipsLimit": 20,
          "maxReferencedTipAgeSeconds": 3,
          "maxApprovers": 2
        }
      },
      "node": {
        "alias": "",
        "showAliasInGetNodeInfo": false,
        "disablePlugins": [
          "Dashboard",
          "MQTT",
          "ZMQ",
          "Prometheus"
        ],
        "enablePlugins": [
          "URTS",
          "WebAPI",
          "Autopeering",
          "WarpSync"{{ if .Values.hornet.spammer }}, "Spammer" {{ end }}
        ]
      },
      "logger": {
        "level": "info",
        "disableCaller": true,
        "encoding": "console",
        "outputPaths": [
          "stdout"
        ]
      },
      "warpsync": {
        "advancementRange": 50
      },
      "spammer": {
        "address": "HORNET99INTEGRATED99SPAMMER999999999999999999999999999999999999999999999999999999",
        "message": "Spamming with HORNET tipselect",
        "tag": "HORNET99INTEGRATED99SPAMMER",
        "tagSemiLazy": "",
        "cpuMaxUsage": {{ .Values.hornet.spammer.cpuMaxUsage }},
        "tpsRateLimit": {{ .Values.hornet.spammer.rateLimit }},
        "bundleSize": 1,
        "valueSpam": false,
        "workers": 1,
        "autostart": true
      },
      "profiling": {
        "bindAddress": "0.0.0.0:6060"
      },
      "prometheus": {
        "bindAddress": "0.0.0.0:9311",
        "goMetrics": false,
        "processMetrics": false,
        "promhttpMetrics": false
      }
    }
